class CfgPatches
{
	class 40th_headgears_conf
	{
		units[]={};
		weapons[]={};
		requiredVersion=1;
		requiredAddons[]=
		{
			"rhs_main"
		};
	};
};
class CfgSkeletons
{
	class Default
	{
		isDiscrete=1;
		skeletonInherit="";
		skeletonBones[]={};
	};
	class OFP2_ManSkeleton
	{
		isDiscrete=0;
		skeletonInherit="";
		skeletonBones[]=
		{
			"Pelvis",
			"",
			"Spine",
			"Pelvis",
			"Spine1",
			"Spine",
			"Spine2",
			"Spine1",
			"Spine3",
			"Spine2",
			"Camera",
			"Pelvis",
			"weapon",
			"Spine1",
			"launcher",
			"Spine1",
			"neck",
			"Spine3",
			"neck1",
			"neck",
			"head",
			"neck1",
			"Face_Hub",
			"head",
			"Face_Jawbone",
			"Face_Hub",
			"Face_Jowl",
			"Face_Jawbone",
			"Face_chopRight",
			"Face_Jawbone",
			"Face_chopLeft",
			"Face_Jawbone",
			"Face_LipLowerMiddle",
			"Face_Jawbone",
			"Face_LipLowerLeft",
			"Face_Jawbone",
			"Face_LipLowerRight",
			"Face_Jawbone",
			"Face_Chin",
			"Face_Jawbone",
			"Face_Tongue",
			"Face_Jawbone",
			"Face_CornerRight",
			"Face_Hub",
			"Face_CheekSideRight",
			"Face_CornerRight",
			"Face_CornerLeft",
			"Face_Hub",
			"Face_CheekSideLeft",
			"Face_CornerLeft",
			"Face_CheekFrontRight",
			"Face_Hub",
			"Face_CheekFrontLeft",
			"Face_Hub",
			"Face_CheekUpperRight",
			"Face_Hub",
			"Face_CheekUpperLeft",
			"Face_Hub",
			"Face_LipUpperMiddle",
			"Face_Hub",
			"Face_LipUpperRight",
			"Face_Hub",
			"Face_LipUpperLeft",
			"Face_Hub",
			"Face_NostrilRight",
			"Face_Hub",
			"Face_NostrilLeft",
			"Face_Hub",
			"Face_Forehead",
			"Face_Hub",
			"Face_BrowFrontRight",
			"Face_Forehead",
			"Face_BrowFrontLeft",
			"Face_Forehead",
			"Face_BrowMiddle",
			"Face_Forehead",
			"Face_BrowSideRight",
			"Face_Forehead",
			"Face_BrowSideLeft",
			"Face_Forehead",
			"Face_Eyelids",
			"Face_Hub",
			"Face_EyelidUpperRight",
			"Face_Hub",
			"Face_EyelidUpperLeft",
			"Face_Hub",
			"Face_EyelidLowerRight",
			"Face_Hub",
			"Face_EyelidLowerLeft",
			"Face_Hub",
			"EyeLeft",
			"Face_Hub",
			"EyeRight",
			"Face_Hub",
			"LeftShoulder",
			"Spine3",
			"LeftArm",
			"LeftShoulder",
			"LeftArmRoll",
			"LeftArm",
			"LeftForeArm",
			"LeftArmRoll",
			"LeftForeArmRoll",
			"LeftForeArm",
			"LeftHand",
			"LeftForeArmRoll",
			"LeftHandRing",
			"LeftHand",
			"LeftHandRing1",
			"LeftHandRing",
			"LeftHandRing2",
			"LeftHandRing1",
			"LeftHandRing3",
			"LeftHandRing2",
			"LeftHandPinky1",
			"LeftHandRing",
			"LeftHandPinky2",
			"LeftHandPinky1",
			"LeftHandPinky3",
			"LeftHandPinky2",
			"LeftHandMiddle1",
			"LeftHand",
			"LeftHandMiddle2",
			"LeftHandMiddle1",
			"LeftHandMiddle3",
			"LeftHandMiddle2",
			"LeftHandIndex1",
			"LeftHand",
			"LeftHandIndex2",
			"LeftHandIndex1",
			"LeftHandIndex3",
			"LeftHandIndex2",
			"LeftHandThumb1",
			"LeftHand",
			"LeftHandThumb2",
			"LeftHandThumb1",
			"LeftHandThumb3",
			"LeftHandThumb2",
			"RightShoulder",
			"Spine3",
			"RightArm",
			"RightShoulder",
			"RightArmRoll",
			"RightArm",
			"RightForeArm",
			"RightArmRoll",
			"RightForeArmRoll",
			"RightForeArm",
			"RightHand",
			"RightForeArmRoll",
			"RightHandRing",
			"RightHand",
			"RightHandRing1",
			"RightHandRing",
			"RightHandRing2",
			"RightHandRing1",
			"RightHandRing3",
			"RightHandRing2",
			"RightHandPinky1",
			"RightHandRing",
			"RightHandPinky2",
			"RightHandPinky1",
			"RightHandPinky3",
			"RightHandPinky2",
			"RightHandMiddle1",
			"RightHand",
			"RightHandMiddle2",
			"RightHandMiddle1",
			"RightHandMiddle3",
			"RightHandMiddle2",
			"RightHandIndex1",
			"RightHand",
			"RightHandIndex2",
			"RightHandIndex1",
			"RightHandIndex3",
			"RightHandIndex2",
			"RightHandThumb1",
			"RightHand",
			"RightHandThumb2",
			"RightHandThumb1",
			"RightHandThumb3",
			"RightHandThumb2",
			"LeftUpLeg",
			"Pelvis",
			"LeftUpLegRoll",
			"LeftUpLeg",
			"LeftLeg",
			"LeftUpLegRoll",
			"LeftLegRoll",
			"LeftLeg",
			"LeftFoot",
			"LeftLegRoll",
			"LeftToeBase",
			"LeftFoot",
			"RightUpLeg",
			"Pelvis",
			"RightUpLegRoll",
			"RightUpLeg",
			"RightLeg",
			"RightUpLegRoll",
			"RightLegRoll",
			"RightLeg",
			"RightFoot",
			"RightLegRoll",
			"RightToeBase",
			"RightFoot"
		};
		pivotsModel="A3\anims_f\data\skeleton\SkeletonPivots.p3d";
	};
};
class CfgModels
{
	class Default
	{
		sectionsInherit="";
		sections[]={};
		skeletonName="";
	};
	class ArmaMan: Default
	{
		htMin=60;
		htMax=1800;
		afMax=30;
		mfMax=0;
		mFact=1;
		tBody=37;
		sections[]=
		{
			"osobnost",
			"Head_Injury",
			"Body_Injury",
			"l_leg_injury",
			"l_arm_injury",
			"r_arm_injury",
			"r_leg_injury",
			"injury_body",
			"injury_legs",
			"injury_hands",
			"clan",
			"clan_sign",
			"Camo",
			"CamoB",
			"Camo1",
			"Camo2",
			"personality",
			"hl",
			"injury_head",
			"insignia",
			"ghillie_hide"
		};
		skeletonName="OFP2_ManSkeleton";
	};
	class Soviet_Panama: ArmaMan
	{
	};
	class Soviet_Panama_1: ArmaMan
	{
	};
};
class cfgWeapons
{
	class HeadgearItem;
	class H_HelmetB;
	class rhs_fieldcap;
	class rhsgref_ssh68_vsr;
	class rhs_ssh68;
	class Panama_Afghanistan: H_HelmetB
	{
		displayName="$STR_PANAMA";
		descriptionShort="$STR_DS_Panama";
		picture="\40th_headgears\ico\panama_ico.paa";
		Scope=2;
		model="\40th_headgears\Soviet_Panama";
		hiddenSelections[]=
		{
			"Camo1"
		};
		hiddenSelectionsTextures[]=
		{
			"40th_headgears\data\panama_co.paa"
		};
		class ItemInfo: HeadgearItem
		{
			hiddenSelections[]=
			{
				"Camo1"
			};
			mass=5;
			uniformModel="\40th_headgears\Soviet_Panama";
			allowedSlots[]={801,901,701,605};
			modelSides[]={6};
		};
	};
	class Panama_Afghanistan1: Panama_Afghanistan
	{
		displayName="$STR_PANAMA";
		Scope=2;
		model="\40th_headgears\Soviet_Panama_1";
		class ItemInfo: HeadgearItem
		{
			hiddenSelections[]=
			{
				"Camo1"
			};
			mass=5;
			uniformModel="\40th_headgears\Soviet_Panama_1";
			allowedSlots[]={801,901,701,605};
			modelSides[]={6};
		};
	};
	class fieldcap_butan: rhs_fieldcap
	{
		descriptionShort="$STR_DS_Butan_cap";
		hiddenSelections[]=
		{
			"Camo1"
		};
		hiddenSelectionsTextures[]=
		{
			"\40th_headgears\data\kepka_butan.paa"
		};
	};
	class ssh68_camo_kzs: rhsgref_ssh68_vsr
	{
		displayName="$STR_ssh68_kzs";
		descriptionShort="$STR_DS_SSh_KZS";
		hiddenSelections[]=
		{
			"Camo2"
		};
		hiddenSelectionsTextures[]=
		{
			"\40th_headgears\data\ssh68_kzs_cover.paa"
		};
	};
	class ssh68_khaki: rhs_ssh68
	{
		displayName="$STR_ssh68_khaki";
		descriptionShort="$STR_DS_SSh_Khaki";
		hiddenSelections[]=
		{
			"camo1"
		};
		hiddenSelectionsTextures[]=
		{
			"\40th_headgears\data\ssh68_co.paa"
		};
	};
	class ssh68_reg: ssh68_khaki
	{
		displayName="$STR_ssh68_reg";
		descriptionShort="$STR_DS_SSh_reg";
		hiddenSelections[]=
		{
			"camo1"
		};
		hiddenSelectionsTextures[]=
		{
			"\40th_headgears\data\ssh68_reg.paa"
		};
	};
	class ssh68_camo_yel: ssh68_khaki
	{
		displayName="$STR_ssh68_cy";
		descriptionShort="$STR_DS_SSh_Camo_yel";
		hiddenSelections[]=
		{
			"camo1"
		};
		hiddenSelectionsTextures[]=
		{
			"\40th_headgears\data\ssh68_camo_y.paa"
		};
	};
	class ssh68_camo_green: ssh68_khaki
	{
		displayName="$STR_ssh68_cg";
		descriptionShort="$STR_DS_SSh_Camo_gr";
		hiddenSelections[]=
		{
			"camo1"
		};
		hiddenSelectionsTextures[]=
		{
			"\40th_headgears\data\ssh68_camo_g.paa"
		};
	};
};
class cfgMods
{
	author="Basher";
	timepacked="1545954556";
};
