class CfgPatches
{
	class Taliban_fighters
	{
		units[]=
		{
			"TBan_Warlord",
			"Afghan_Civilian6NH",
			"Afghan_Civilian6",
			"Afghan_Civilian5",
			"Afghan_Civilian4",
			"Afghan_Civilian3",
			"Afghan_Civilian2",
			"Afghan_Civilian1",
			"Afghan_Civilian3NH",
			"Afghan_Civilian2NH",
			"Afghan_Civilian1NH",
			"Tban_O_Offroad_01_F",
			"TBan_Fighter6NH",
			"TBan_Fighter6",
			"TBan_Fighter5",
			"TBan_Fighter4",
			"TBan_Fighter3NH",
			"TBan_Fighter2NH",
			"TBan_Fighter1NH",
			"TBan_Fighter3",
			"TBan_Fighter2",
			"TBan_Fighter1",
			"TBan_Recruit6",
			"TBan_Recruit6NH",
			"TBan_Recruit5",
			"TBan_Recruit4",
			"TBan_Recruit3NH",
			"TBan_Recruit3",
			"TBan_Recruit2NH",
			"TBan_Recruit2",
			"TBan_Recruit1",
			"TBan_Recruit1NH"
		};
		weapons[]={};
		requiredVersion=1.5;
		requiredAddons[]=
		{
			"A3_Characters_F",
			"A3_Data_F",
			"A3_Soft_F"
		};
	};
};
class CfgVehicleClasses
{
	class TBan
	{
		displayName="Taliban";
	};
	class AFGCIV
	{
		displayName="Afghan Civilians";
	};
};
class CfgFactionClasses
{
	class AFGCIV
	{
		displayName="Afghan Civilians";
		flag="\Taliban_fighters\data\Flags\flag_afghanistan_co.paa";
		icon="\Taliban_fighters\data\cfgfactionclasses_afgciv.paa";
		priority=1;
		side=3;
	};
	class Tban
	{
		displayName="Taliban";
		flag="\Taliban_Fighters\data\Aggressor\flag_taliban_co.paa";
		icon="\Taliban_Fighters\data\cfgfactionclasses_Tban.paa";
		priority=1;
		side=0;
	};
};
class CfgVehicles
{
	class O_Soldier_base_F;
	class TBan_Fighter1: O_Soldier_base_F
	{
		nameSound="veh_infantry_SF_s";
		author="EricJ";
		_generalMacro="TBan_Fighter1";
		scope=2;
		scopeCurator=2;
		side=0;
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_TK",
			"G_GUERIL_default",
			"NoGlasses"
		};
		displayName="Taliban Leader";
		faction="Tban";
		vehicleClass="Men";
		detectSkill=70;
		items[]=
		{
			"FirstAidKit"
		};
		respawnitems[]=
		{
			"FirstAidKit"
		};
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		magazines[]={};
		respawnMagazines[]={};
		linkedItems[]={};
		respawnLinkedItems[]={};
		model="\Taliban_Fighters\Uniforms\Afghan_01";
		modelSides[]={3};
		uniformClass="U_Afghan01";
	};
	class TBan_Fighter1NH: O_Soldier_base_F
	{
		nameSound="veh_infantry_SF_s";
		author="EricJ";
		_generalMacro="TBan_Fighter1";
		scope=2;
		scopeCurator=2;
		side=0;
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_TK",
			"G_GUERIL_default",
			"NoGlasses"
		};
		displayName="Taliban Leader (No Hat)";
		faction="Tban";
		vehicleClass="Men";
		detectSkill=70;
		items[]=
		{
			"FirstAidKit"
		};
		respawnitems[]=
		{
			"FirstAidKit"
		};
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		magazines[]={};
		respawnMagazines[]={};
		linkedItems[]={};
		respawnLinkedItems[]={};
		model="\Taliban_Fighters\Uniforms\Afghan_01NH";
		modelSides[]={3};
		uniformClass="U_Afghan01NH";
	};
	class TBan_Fighter2: TBan_Fighter1
	{
		nameSound="veh_infantry_SF_s";
		author="EricJ";
		_generalMacro="TBan_Fighter1";
		scope=2;
		scopeCurator=2;
		side=0;
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_TK",
			"G_GUERIL_default",
			"NoGlasses"
		};
		displayName="Taliban Fighter 1";
		faction="Tban";
		vehicleClass="Men";
		detectSkill=60;
		items[]={};
		respawnitems[]={};
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		magazines[]={};
		respawnMagazines[]={};
		linkedItems[]={};
		respawnLinkedItems[]={};
		model="\Taliban_Fighters\Uniforms\Afghan_02";
		modelSides[]={3};
		uniformClass="U_Afghan02";
	};
	class TBan_Fighter2NH: TBan_Fighter1
	{
		nameSound="veh_infantry_SF_s";
		author="EricJ";
		_generalMacro="TBan_Fighter1";
		scope=2;
		scopeCurator=2;
		side=0;
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_TK",
			"G_GUERIL_default",
			"NoGlasses"
		};
		displayName="Taliban Fighter 1 (No Hat)";
		faction="Tban";
		vehicleClass="Men";
		detectSkill=60;
		items[]={};
		respawnitems[]={};
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		magazines[]={};
		respawnMagazines[]={};
		linkedItems[]={};
		respawnLinkedItems[]={};
		model="\Taliban_Fighters\Uniforms\Afghan_02NH";
		modelSides[]={3};
		uniformClass="U_Afghan02";
	};
	class TBan_Fighter3: TBan_Fighter1
	{
		nameSound="veh_infantry_SF_s";
		author="EricJ";
		_generalMacro="TBan_Fighter3";
		scope=2;
		scopeCurator=2;
		side=0;
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_TK",
			"G_GUERIL_default",
			"NoGlasses"
		};
		displayName="Taliban Fighter 2";
		faction="Tban";
		vehicleClass="Men";
		detectSkill=60;
		items[]={};
		respawnitems[]={};
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		magazines[]={};
		respawnMagazines[]={};
		linkedItems[]={};
		respawnLinkedItems[]={};
		model="\Taliban_Fighters\Uniforms\Afghan_03";
		modelSides[]={3};
		uniformClass="U_Afghan03";
	};
	class TBan_Fighter3NH: TBan_Fighter1
	{
		nameSound="veh_infantry_SF_s";
		author="EricJ";
		_generalMacro="TBan_Fighter3";
		scope=2;
		scopeCurator=2;
		side=0;
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_TK",
			"G_GUERIL_default",
			"NoGlasses"
		};
		displayName="Taliban Fighter 2";
		faction="Tban";
		vehicleClass="Men";
		detectSkill=60;
		items[]={};
		respawnitems[]={};
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		magazines[]={};
		respawnMagazines[]={};
		linkedItems[]={};
		respawnLinkedItems[]={};
		model="\Taliban_Fighters\Uniforms\Afghan_03NH";
		modelSides[]={3};
		uniformClass="U_Afghan03NH";
	};
	class TBan_Fighter4: TBan_Fighter1
	{
		nameSound="veh_infantry_SF_s";
		author="EricJ";
		_generalMacro="TBan_Fighter4";
		scope=2;
		scopeCurator=2;
		side=0;
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_TK",
			"G_GUERIL_default",
			"NoGlasses"
		};
		displayName="Taliban Fighter 3";
		faction="Tban";
		vehicleClass="Men";
		detectSkill=50;
		items[]={};
		respawnitems[]={};
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		magazines[]={};
		respawnMagazines[]={};
		linkedItems[]={};
		respawnLinkedItems[]={};
		model="\Taliban_Fighters\Uniforms\Afghan_04";
		modelSides[]={3};
		uniformClass="U_Afghan04";
	};
	class TBan_Fighter5: TBan_Fighter1
	{
		nameSound="veh_infantry_SF_s";
		author="EricJ";
		_generalMacro="TBan_Fighter5";
		scope=2;
		scopeCurator=2;
		side=0;
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_TK",
			"G_GUERIL_default",
			"NoGlasses"
		};
		displayName="Taliban Fighter 4";
		faction="Tban";
		vehicleClass="Men";
		detectSkill=50;
		items[]={};
		respawnitems[]={};
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		magazines[]={};
		respawnMagazines[]={};
		linkedItems[]={};
		respawnLinkedItems[]={};
		model="\Taliban_Fighters\Uniforms\Afghan_05";
		modelSides[]={3};
		uniformClass="U_Afghan05";
	};
	class TBan_Fighter6: TBan_Fighter1
	{
		nameSound="veh_infantry_SF_s";
		author="EricJ";
		_generalMacro="TBan_Fighter6";
		scope=2;
		scopeCurator=2;
		side=0;
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_TK",
			"G_GUERIL_default",
			"NoGlasses"
		};
		displayName="Taliban Fighter 5";
		faction="Tban";
		vehicleClass="Men";
		detectSkill=50;
		items[]={};
		respawnitems[]={};
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		magazines[]={};
		respawnMagazines[]={};
		linkedItems[]={};
		respawnLinkedItems[]={};
		model="\Taliban_Fighters\Uniforms\Afghan_06";
		modelSides[]={3};
		uniformClass="U_Afghan06";
	};
	class TBan_Fighter6NH: TBan_Fighter1
	{
		nameSound="veh_infantry_SF_s";
		author="EricJ";
		_generalMacro="TBan_Fighter6";
		scope=2;
		scopeCurator=2;
		side=0;
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_TK",
			"G_GUERIL_default",
			"NoGlasses"
		};
		displayName="Taliban Fighter 5 (No Hat)";
		faction="Tban";
		vehicleClass="Men";
		detectSkill=50;
		items[]={};
		respawnitems[]={};
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		magazines[]={};
		respawnMagazines[]={};
		linkedItems[]={};
		respawnLinkedItems[]={};
		model="\Taliban_Fighters\Uniforms\Afghan_06NH";
		modelSides[]={3};
		uniformClass="U_Afghan06NH";
	};
	class TBan_Warlord: TBan_Fighter1
	{
		nameSound="veh_infantry_SF_s";
		author="EricJ";
		_generalMacro="TBan_Fighter3";
		scope=2;
		scopeCurator=2;
		side=0;
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_TK",
			"G_GUERIL_default",
			"NoGlasses"
		};
		displayName="Taliban Warlord";
		faction="Tban";
		vehicleClass="Men";
		detectSkill=80;
		items[]=
		{
			"FirstAidKit"
		};
		respawnitems[]=
		{
			"FirstAidKit"
		};
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		magazines[]={};
		respawnMagazines[]={};
		linkedItems[]={};
		respawnLinkedItems[]={};
		model="\Taliban_Fighters\Uniforms\Afghan_03";
		modelSides[]={3};
		uniformClass="U_Afghan03";
	};
	class TBan_Sniper: TBan_Fighter1
	{
		dlc="u100";
		nameSound="veh_infantry_SF_s";
		author="EricJ";
		_generalMacro="TBan_Fighter5";
		scope=2;
		scopeCurator=2;
		side=0;
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_TK",
			"G_GUERIL_default",
			"NoGlasses"
		};
		displayName="Taliban Sniper";
		faction="Tban";
		vehicleClass="Men";
		detectSkill=55;
		items[]={};
		respawnitems[]={};
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		magazines[]={};
		respawnMagazines[]={};
		linkedItems[]={};
		respawnLinkedItems[]={};
		model="\u100_c\Gear\Afghan_05";
		modelSides[]={3};
		uniformClass="U_Afghan05";
	};
	class Haji_Matin: TBan_Fighter1
	{
		nameSound="veh_infantry_SF_s";
		author="EricJ";
		_generalMacro="TBan_Fighter3";
		scope=2;
		scopeCurator=2;
		side=0;
		identityTypes[]=
		{
			"Nikos",
			"NoGlasses"
		};
		displayName="Haji Matin (HVT)";
		faction="Tban";
		vehicleClass="Men";
		detectSkill=80;
		items[]=
		{
			"FirstAidKit"
		};
		respawnitems[]=
		{
			"FirstAidKit"
		};
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		magazines[]={};
		respawnMagazines[]={};
		linkedItems[]={};
		respawnLinkedItems[]={};
		model="\Taliban_Fighters\Uniforms\Afghan_03";
		modelSides[]={3};
		uniformClass="U_Afghan03";
	};
	class TBan_Recruit: TBan_Fighter1
	{
		dlc="u100";
		nameSound="veh_infantry_SF_s";
		author="EricJ";
		_generalMacro="TBan_Fighter1";
		scope=2;
		scopeCurator=2;
		side=0;
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_TK",
			"G_GUERIL_default",
			"NoGlasses"
		};
		displayName="Taliban Recruit 1";
		faction="Tban";
		vehicleClass="Men";
		detectSkill=30;
		items[]=
		{
			"FirstAidKit"
		};
		respawnitems[]=
		{
			"FirstAidKit"
		};
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		magazines[]={};
		respawnMagazines[]={};
		linkedItems[]={};
		respawnLinkedItems[]={};
		model="\Taliban_Fighters\Uniforms\Afghan_01";
		modelSides[]={3};
		uniformClass="U_Afghan01";
	};
	class TBan_Recruit1NH: TBan_Fighter1
	{
		dlc="u100";
		nameSound="veh_infantry_SF_s";
		author="EricJ";
		_generalMacro="TBan_Fighter1";
		scope=2;
		scopeCurator=2;
		side=0;
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_TK",
			"G_GUERIL_default"
		};
		displayName="Taliban Recruit 1 (No Hat)";
		faction="Tban";
		vehicleClass="Men";
		detectSkill=30;
		items[]=
		{
			"FirstAidKit"
		};
		respawnitems[]=
		{
			"FirstAidKit"
		};
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		magazines[]={};
		respawnMagazines[]={};
		linkedItems[]={};
		respawnLinkedItems[]={};
		model="\Taliban_Fighters\Uniforms\Afghan_01NH";
		modelSides[]={3};
		uniformClass="U_Afghan01NH";
	};
	class TBan_Recruit2: TBan_Fighter1
	{
		dlc="u100";
		nameSound="veh_infantry_SF_s";
		author="EricJ";
		_generalMacro="TBan_Fighter1";
		scope=2;
		scopeCurator=2;
		side=0;
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_TK",
			"G_GUERIL_default",
			"NoGlasses"
		};
		displayName="Taliban Recruit 2";
		faction="Tban";
		vehicleClass="Men";
		detectSkill=30;
		items[]={};
		respawnitems[]={};
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		magazines[]={};
		respawnMagazines[]={};
		linkedItems[]={};
		respawnLinkedItems[]={};
		model="\Taliban_Fighters\Uniforms\Afghan_02";
		modelSides[]={3};
		uniformClass="U_Afghan02";
	};
	class TBan_Recruit2NH: TBan_Fighter1
	{
		dlc="u100";
		nameSound="veh_infantry_SF_s";
		author="EricJ";
		_generalMacro="TBan_Fighter1";
		scope=2;
		scopeCurator=2;
		side=0;
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_TK",
			"G_GUERIL_default",
			"NoGlasses"
		};
		displayName="Taliban Recruit 2 (No Hat)";
		faction="Tban";
		vehicleClass="Men";
		detectSkill=20;
		backpack="";
		items[]={};
		respawnitems[]={};
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		magazines[]={};
		respawnMagazines[]={};
		linkedItems[]={};
		respawnLinkedItems[]={};
		model="\Taliban_Fighters\Uniforms\Afghan_02NH";
		modelSides[]={3};
		uniformClass="U_Afghan02NH";
	};
	class TBan_Recruit3: TBan_Fighter1
	{
		dlc="u100";
		nameSound="veh_infantry_SF_s";
		author="EricJ";
		_generalMacro="TBan_Fighter3";
		scope=2;
		scopeCurator=2;
		side=0;
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_TK",
			"G_GUERIL_default",
			"NoGlasses"
		};
		displayName="Taliban Recruit 3";
		faction="Tban";
		vehicleClass="Men";
		detectSkill=30;
		items[]={};
		respawnitems[]={};
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		magazines[]={};
		respawnMagazines[]={};
		linkedItems[]={};
		respawnLinkedItems[]={};
		model="\Taliban_Fighters\Uniforms\Afghan_03";
		modelSides[]={3};
		uniformClass="U_Afghan03";
	};
	class TBan_Recruit3NH: TBan_Fighter1
	{
		dlc="u100";
		nameSound="veh_infantry_SF_s";
		author="EricJ";
		_generalMacro="TBan_Fighter3";
		scope=2;
		scopeCurator=2;
		side=0;
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_TK",
			"G_GUERIL_default",
			"NoGlasses"
		};
		displayName="Taliban Recruit 3 (No Hat)";
		faction="Tban";
		vehicleClass="Men";
		detectSkill=25;
		items[]={};
		respawnitems[]={};
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		magazines[]={};
		respawnMagazines[]={};
		linkedItems[]={};
		respawnLinkedItems[]={};
		model="\Taliban_Fighters\Uniforms\Afghan_03NH";
		modelSides[]={3};
		uniformClass="U_Afghan03NH";
	};
	class TBan_Recruit4: TBan_Fighter1
	{
		dlc="u100";
		nameSound="veh_infantry_SF_s";
		author="EricJ";
		_generalMacro="TBan_Fighter4";
		scope=2;
		scopeCurator=2;
		side=0;
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_TK",
			"G_GUERIL_default",
			"NoGlasses"
		};
		displayName="Taliban Recruit 4";
		faction="Tban";
		vehicleClass="Men";
		detectSkill=35;
		items[]={};
		respawnitems[]={};
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		magazines[]={};
		respawnMagazines[]={};
		linkedItems[]={};
		respawnLinkedItems[]={};
		model="\Taliban_Fighters\Uniforms\Afghan_04";
		modelSides[]={3};
		uniformClass="U_Afghan04";
	};
	class TBan_Recruit5: TBan_Fighter1
	{
		dlc="u100";
		nameSound="veh_infantry_SF_s";
		author="EricJ";
		_generalMacro="TBan_Fighter5";
		scope=2;
		scopeCurator=2;
		side=0;
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_TK",
			"G_GUERIL_default",
			"NoGlasses"
		};
		displayName="Taliban Recruit 5";
		faction="Tban";
		vehicleClass="Men";
		detectSkill=25;
		items[]={};
		respawnitems[]={};
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		magazines[]={};
		respawnMagazines[]={};
		linkedItems[]={};
		respawnLinkedItems[]={};
		model="\Taliban_Fighters\Uniforms\Afghan_05";
		modelSides[]={3};
		uniformClass="U_Afghan05";
	};
	class TBan_Recruit6: TBan_Fighter1
	{
		dlc="u100";
		nameSound="veh_infantry_SF_s";
		author="EricJ";
		_generalMacro="TBan_Fighter6";
		scope=2;
		scopeCurator=2;
		side=0;
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_TK",
			"G_GUERIL_default",
			"NoGlasses"
		};
		displayName="Taliban Recruit 6";
		faction="Tban";
		vehicleClass="Men";
		detectSkill=30;
		items[]={};
		respawnitems[]={};
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		magazines[]={};
		respawnMagazines[]={};
		linkedItems[]={};
		respawnLinkedItems[]={};
		model="\Taliban_Fighters\Uniforms\Afghan_06";
		modelSides[]={3};
		uniformClass="U_Afghan06";
	};
	class TBan_Recruit6NH: TBan_Fighter1
	{
		dlc="u100";
		nameSound="veh_infantry_SF_s";
		author="EricJ";
		_generalMacro="TBan_Fighter6";
		scope=2;
		scopeCurator=2;
		side=0;
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_TK",
			"G_GUERIL_default",
			"NoGlasses"
		};
		displayName="Taliban Recruit 6 (No Hat)";
		faction="Tban";
		vehicleClass="Men";
		detectSkill=30;
		items[]={};
		respawnitems[]={};
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		magazines[]={};
		respawnMagazines[]={};
		linkedItems[]={};
		respawnLinkedItems[]={};
		model="\Taliban_Fighters\Uniforms\Afghan_06NH";
		modelSides[]={3};
		uniformClass="U_Afghan06NH";
	};
	class Afghan_civilian1: TBan_Fighter1
	{
		nameSound="veh_infantry_SF_s";
		author="EricJ";
		_generalMacro="Afghan_civilian1";
		scope=2;
		scopeCurator=2;
		side=3;
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_TK",
			"G_GUERIL_default",
			"NoGlasses"
		};
		displayName="Afghan Village Leader";
		faction="AFGCIV";
		vehicleClass="Men";
		detectSkill=70;
		items[]={};
		respawnitems[]={};
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		magazines[]={};
		respawnMagazines[]={};
		linkedItems[]={};
		respawnLinkedItems[]={};
		model="\Taliban_fighters\Uniforms\Afghan_01";
		modelSides[]={3};
		headgearProbability=0;
		uniformClass="U_Afghan01";
	};
	class Afghan_civilian1NH: TBan_Fighter1
	{
		nameSound="veh_infantry_SF_s";
		author="EricJ";
		_generalMacro="Afghan_civilian1";
		scope=2;
		scopeCurator=2;
		side=3;
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_TK",
			"G_GUERIL_default",
			"NoGlasses"
		};
		displayName="Afghan Village Leader (No Hat)";
		faction="AFGCIV";
		vehicleClass="Men";
		detectSkill=70;
		items[]={};
		respawnitems[]={};
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		magazines[]={};
		respawnMagazines[]={};
		linkedItems[]={};
		respawnLinkedItems[]={};
		model="\Taliban_fighters\Uniforms\Afghan_01NH";
		modelSides[]={3};
		headgearProbability=0;
		uniformClass="U_Afghan01NH";
	};
	class Afghan_Civilian2: Afghan_civilian1
	{
		nameSound="veh_infantry_SF_s";
		author="EricJ";
		_generalMacro="Afghan_Civilian2";
		scope=2;
		scopeCurator=2;
		side=3;
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_TK",
			"G_GUERIL_default",
			"NoGlasses"
		};
		displayName="Afghan Civilian 1";
		faction="AFGCIV";
		vehicleClass="Men";
		detectSkill=55;
		items[]={};
		respawnitems[]={};
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		magazines[]={};
		respawnMagazines[]={};
		linkedItems[]={};
		respawnLinkedItems[]={};
		model="\Taliban_fighters\Uniforms\Afghan_02";
		modelSides[]={3};
		headgearProbability=0;
		uniformClass="U_Afghan02";
	};
	class Afghan_Civilian2NH: Afghan_civilian1
	{
		nameSound="veh_infantry_SF_s";
		author="EricJ";
		_generalMacro="Afghan_Civilian2";
		scope=2;
		scopeCurator=2;
		side=3;
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_TK",
			"G_GUERIL_default",
			"NoGlasses"
		};
		displayName="Afghan Civilian 1 (No Hat)";
		faction="AFGCIV";
		vehicleClass="Men";
		detectSkill=55;
		items[]={};
		respawnitems[]={};
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		magazines[]={};
		respawnMagazines[]={};
		linkedItems[]={};
		respawnLinkedItems[]={};
		model="\Taliban_fighters\Uniforms\Afghan_02NH";
		modelSides[]={3};
		headgearProbability=0;
		uniformClass="U_Afghan02NH";
	};
	class Afghan_civilian3: Afghan_civilian1
	{
		nameSound="veh_infantry_SF_s";
		author="EricJ";
		_generalMacro="Afghan_civilian3";
		scope=2;
		scopeCurator=2;
		side=3;
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_TK",
			"G_GUERIL_default",
			"NoGlasses"
		};
		displayName="Afghan Civilian 2";
		faction="AFGCIV";
		vehicleClass="Men";
		detectSkill=55;
		items[]={};
		respawnitems[]={};
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		magazines[]={};
		respawnMagazines[]={};
		linkedItems[]={};
		respawnLinkedItems[]={};
		model="\Taliban_fighters\Uniforms\Afghan_03";
		modelSides[]={3};
		headgearProbability=0;
		uniformClass="U_Afghan03";
	};
	class Afghan_civilian3NH: Afghan_civilian1
	{
		nameSound="veh_infantry_SF_s";
		author="EricJ";
		_generalMacro="Afghan_civilian3";
		scope=2;
		scopeCurator=2;
		side=3;
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_TK",
			"G_GUERIL_default",
			"NoGlasses"
		};
		displayName="Afghan Civilian 2 (No Hat)";
		faction="AFGCIV";
		vehicleClass="Men";
		detectSkill=55;
		items[]={};
		respawnitems[]={};
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		magazines[]={};
		respawnMagazines[]={};
		linkedItems[]={};
		respawnLinkedItems[]={};
		model="\Taliban_fighters\Uniforms\Afghan_03NH";
		modelSides[]={3};
		headgearProbability=0;
		uniformClass="U_Afghan03NH";
	};
	class Afghan_Civilian4: Afghan_civilian1
	{
		nameSound="veh_infantry_SF_s";
		author="EricJ";
		_generalMacro="Afghan_Civilian4";
		scope=2;
		scopeCurator=2;
		side=3;
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_TK",
			"G_GUERIL_default",
			"NoGlasses"
		};
		displayName="Afghan Civilian 3";
		faction="AFGCIV";
		vehicleClass="Men";
		detectSkill=55;
		items[]={};
		respawnitems[]={};
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		magazines[]={};
		respawnMagazines[]={};
		linkedItems[]={};
		respawnLinkedItems[]={};
		model="\Taliban_fighters\Uniforms\Afghan_04";
		modelSides[]={3};
		headgearProbability=0;
		uniformClass="U_Afghan04";
	};
	class Afghan_Civilian5: Afghan_civilian1
	{
		nameSound="veh_infantry_SF_s";
		author="EricJ";
		_generalMacro="Afghan_Civilian5";
		scope=2;
		scopeCurator=2;
		side=3;
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_TK",
			"G_GUERIL_default",
			"NoGlasses"
		};
		displayName="Afghan Civilian 4";
		faction="AFGCIV";
		vehicleClass="Men";
		detectSkill=55;
		items[]={};
		respawnitems[]={};
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		magazines[]={};
		respawnMagazines[]={};
		linkedItems[]={};
		respawnLinkedItems[]={};
		model="\Taliban_fighters\Uniforms\Afghan_05";
		modelSides[]={3};
		headgearProbability=0;
		uniformClass="U_Afghan05";
	};
	class Afghan_Civilian6: Afghan_civilian1
	{
		nameSound="veh_infantry_SF_s";
		author="EricJ";
		_generalMacro="Afghan_Civilian6";
		scope=2;
		scopeCurator=2;
		side=3;
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_TK",
			"G_GUERIL_default",
			"NoGlasses"
		};
		displayName="Afghan Civilian 5";
		faction="AFGCIV";
		vehicleClass="Men";
		detectSkill=55;
		items[]={};
		respawnitems[]={};
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		magazines[]={};
		respawnMagazines[]={};
		linkedItems[]={};
		respawnLinkedItems[]={};
		model="\Taliban_fighters\Uniforms\Afghan_06";
		modelSides[]={3};
		headgearProbability=0;
		uniformClass="U_Afghan06";
	};
	class Afghan_Civilian6NH: Afghan_civilian1
	{
		nameSound="veh_infantry_SF_s";
		author="EricJ";
		_generalMacro="Afghan_Civilian6";
		scope=2;
		scopeCurator=2;
		side=3;
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_TK",
			"G_GUERIL_default",
			"NoGlasses"
		};
		displayName="Afghan Civilian 5 (No Hat)";
		faction="AFGCIV";
		vehicleClass="Men";
		detectSkill=55;
		items[]={};
		respawnitems[]={};
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		magazines[]={};
		respawnMagazines[]={};
		linkedItems[]={};
		respawnLinkedItems[]={};
		model="\Taliban_fighters\Uniforms\Afghan_06NH";
		modelSides[]={3};
		headgearProbability=0;
		uniformClass="U_Afghan06NH";
	};
};
class CfgWeapons
{
	class InventoryItem_Base_F;
	class HeadgearItem;
	class UniformItem: InventoryItem_Base_F
	{
		type=801;
	};
	class ItemCore;
	class Uniform_Base;
	class U_Afghan01: Uniform_Base
	{
		author="EricJ";
		scope=2;
		displayName="Afghan Clothes 1";
		picture="\A3\characters_f\data\ui\icon_U_Citizen_ca.paa";
		model="\Taliban_Fighters\Uniforms\Afghan_01.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"Taliban_Fighters\data\tak_civil01_1_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="TBan_Fighter1";
			containerClass="Supply30";
			passThrough=1;
			mass=30;
		};
	};
	class U_Afghan02: Uniform_Base
	{
		author="EricJ";
		scope=2;
		displayName="Afghan Clothes 2";
		picture="\A3\characters_f\data\ui\icon_U_Citizen_ca.paa";
		model="\Taliban_Fighters\Uniforms\Afghan_02.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"Taliban_Fighters\data\tak_civil02_1_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="TBan_Fighter2";
			containerClass="Supply30";
			passThrough=1;
			mass=30;
		};
	};
	class U_Afghan03: Uniform_Base
	{
		author="EricJ";
		scope=2;
		displayName="Afghan Clothes 3";
		picture="\A3\characters_f\data\ui\icon_U_Citizen_ca.paa";
		model="\Taliban_Fighters\Uniforms\Afghan_03.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"Taliban_Fighters\data\tak_civil03_1_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="TBan_Fighter3";
			containerClass="Supply30";
			passThrough=1;
			mass=30;
		};
	};
	class U_Afghan04: Uniform_Base
	{
		author="EricJ";
		scope=2;
		displayName="Afghan Clothes 4";
		picture="\A3\characters_f\data\ui\icon_U_Citizen_ca.paa";
		model="\Taliban_Fighters\Uniforms\Afghan_04.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"Taliban_Fighters\data\tak_civil04_1_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="TBan_Fighter4";
			containerClass="Supply30";
			mass=30;
			passThrough=1;
		};
	};
	class U_Afghan05: Uniform_Base
	{
		author="EricJ";
		scope=2;
		displayName="Afghan Clothes 5";
		picture="\A3\characters_f\data\ui\icon_U_Citizen_ca.paa";
		model="\Taliban_Fighters\Uniforms\Afghan_05.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"Taliban_Fighters\data\tak_civil05_1_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="TBan_Fighter5";
			containerClass="Supply30";
			mass=30;
			passThrough=1;
		};
	};
	class U_Afghan06: Uniform_Base
	{
		author="EricJ";
		scope=2;
		displayName="Afghan Clothes 6";
		picture="\A3\characters_f\data\ui\icon_U_Citizen_ca.paa";
		model="\Taliban_Fighters\Uniforms\Afghan_06.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"Taliban_Fighters\data\tak_civil06_1_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="TBan_Fighter6";
			containerClass="Supply30";
			mass=30;
			passThrough=1;
		};
	};
	class U_Afghan01NH: Uniform_Base
	{
		author="EricJ";
		scope=2;
		displayName="Afghan Clothes 1 (No Hat)";
		picture="\A3\characters_f\data\ui\icon_U_Citizen_ca.paa";
		model="\Taliban_Fighters\Uniforms\Afghan_01NH.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"Taliban_Fighters\data\tak_civil01_1_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="TBan_Fighter1NH";
			containerClass="Supply30";
			mass=30;
			passThrough=1;
		};
	};
	class U_Afghan02NH: Uniform_Base
	{
		author="EricJ";
		scope=2;
		displayName="Afghan Clothes 2 (No Hat)";
		picture="\A3\characters_f\data\ui\icon_U_Citizen_ca.paa";
		model="\Taliban_Fighters\Uniforms\Afghan_02NH.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"Taliban_Fighters\data\tak_civil02_1_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="TBan_Fighter2NH";
			containerClass="Supply30";
			mass=30;
			passThrough=1;
		};
	};
	class U_Afghan03NH: Uniform_Base
	{
		author="EricJ";
		scope=2;
		displayName="Afghan Clothes 3 (No Hat)";
		picture="\A3\characters_f\data\ui\icon_U_Citizen_ca.paa";
		model="\Taliban_Fighters\Uniforms\Afghan_03NH.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"Taliban_Fighters\data\tak_civil03_1_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="TBan_Fighter3NH";
			passThrough=1;
			containerClass="Supply30";
			mass=30;
		};
	};
	class U_Afghan06NH: Uniform_Base
	{
		author="EricJ";
		scope=2;
		displayName="Afghan Clothes 6 (No Hat)";
		picture="\A3\characters_f\data\ui\icon_U_Citizen_ca.paa";
		model="\Taliban_Fighters\Uniforms\Afghan_06NH.p3d";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"Taliban_Fighters\data\tak_civil06_1_co.paa"
		};
		class ItemInfo: UniformItem
		{
			uniformModel="-";
			uniformClass="TBan_Fighter6NH";
			armor=0;
			passThrough=1;
			containerClass="Supply30";
			mass=30;
		};
	};
	class H_HelmetB;
	class Afghan_01Hat: H_HelmetB
	{
		author="$STR_A3_Bohemia_Interactive";
		_generalMacro="Afghan_01Hat";
		displayName="Afghan Hat 1";
		picture="\Taliban_Fighters\data\ui\Afghan_01Hat.paa";
		model="\Taliban_Fighters\gear\Afghan_01Hat";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"Taliban_Fighters\data\tak_civil01_1_co.paa"
		};
		class ItemInfo: HeadgearItem
		{
			mass=4;
			uniformModel="\Taliban_Fighters\gear\Afghan_01Hat.p3d";
			allowedSlots[]={801,901,701,605};
			modelSides[]={6};
			armor=0;
			passThrough=1;
		};
	};
	class Afghan_02Hat: H_HelmetB
	{
		author="$STR_A3_Bohemia_Interactive";
		_generalMacro="Afghan_01Hat";
		displayName="Afghan Hat 2";
		picture="\Taliban_Fighters\data\ui\Afghan_02Hat.paa";
		model="\Taliban_Fighters\gear\Afghan_02Hat";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"Taliban_Fighters\data\tak_civil02_1_co.paa"
		};
		class ItemInfo: HeadgearItem
		{
			mass=4;
			uniformModel="\Taliban_Fighters\gear\Afghan_02Hat.p3d";
			allowedSlots[]={801,901,701,605};
			modelSides[]={6};
			passThrough=1;
		};
	};
	class Afghan_03Hat: H_HelmetB
	{
		author="$STR_A3_Bohemia_Interactive";
		_generalMacro="Afghan_01Hat";
		displayName="Afghan Hat 3";
		picture="\Taliban_Fighters\data\ui\Afghan_03Hat.paa";
		model="\Taliban_Fighters\gear\Afghan_03Hat";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"Taliban_Fighters\data\tak_civil03_1_co.paa"
		};
		class ItemInfo: HeadgearItem
		{
			mass=4;
			uniformModel="\Taliban_Fighters\gear\Afghan_03Hat.p3d";
			allowedSlots[]={801,901,701,605};
			modelSides[]={6};
			passThrough=1;
		};
	};
	class Afghan_04Hat: H_HelmetB
	{
		author="$STR_A3_Bohemia_Interactive";
		_generalMacro="Afghan_01Hat";
		displayName="Afghan Hat 4";
		picture="\Taliban_Fighters\data\UI\Afghan_04Hat.paa";
		model="\Taliban_Fighters\gear\Afghan_04Hat";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"Taliban_Fighters\data\tak_civil04_1_co.paa"
		};
		class ItemInfo: HeadgearItem
		{
			mass=4;
			uniformModel="\Taliban_Fighters\gear\Afghan_04Hat.p3d";
			allowedSlots[]={801,901,701,605};
			modelSides[]={6};
			passThrough=1;
		};
	};
	class Afghan_05Hat: H_HelmetB
	{
		author="$STR_A3_Bohemia_Interactive";
		_generalMacro="Afghan_01Hat";
		displayName="Afghan Hat 5";
		picture="\Taliban_Fighters\data\UI\Afghan_05Hat.paa";
		model="\Taliban_Fighters\gear\Afghan_05Hat";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"Taliban_Fighters\data\tak_civil05_1_co.paa"
		};
		class ItemInfo: HeadgearItem
		{
			mass=4;
			uniformModel="\Taliban_Fighters\gear\Afghan_05Hat.p3d";
			allowedSlots[]={801,901,701,605};
			modelSides[]={6};
			passThrough=1;
		};
	};
	class Afghan_06Hat: H_HelmetB
	{
		author="$STR_A3_Bohemia_Interactive";
		_generalMacro="Afghan_01Hat";
		displayName="Afghan Hat 6";
		picture="\Taliban_Fighters\data\ui\Afghan_06Hat.paa";
		model="\Taliban_Fighters\gear\Afghan_06Hat";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"Taliban_Fighters\data\tak_civil06_1_co.paa"
		};
		class ItemInfo: HeadgearItem
		{
			mass=4;
			uniformModel="\Taliban_Fighters\gear\Afghan_06Hat.p3d";
			allowedSlots[]={801,901,701,605};
			modelSides[]={6};
			passThrough=1;
		};
	};
};
class cfgMods
{
	author="76561198016000690";
	timepacked="1475280458";
};
